---
title: "Automated Measurement Report"
format: html
---

## E800

Next I will show the plots done on the measurement point E800.

### 20251204_141433_STE-01_E800.csv (2025-12-04)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251204_141433_STE-01_E800.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251205_044520_STE-01_E800.csv (2025-12-05)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251205_044520_STE-01_E800.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

## PEC

Next I will show the plots done on the measurement point PEC.

### 20251201_155248_STE-03_PEC.csv (2025-12-01)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251201_155248_STE-03_PEC.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

## STE-02

Next I will show the plots done on the measurement point STE-02.

### 20251104_103620_STE-02.csv (2025-11-04)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251104_103620_STE-02.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251114_112101_STE-02.csv (2025-11-14)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251114_112101_STE-02.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251117_092425_STE-02.csv (2025-11-17)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251117_092425_STE-02.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

## STE-03

Next I will show the plots done on the measurement point STE-03.

### 20251027_143957_STE-03.csv (2025-10-27)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251027_143957_STE-03.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251028_110853_STE-03.csv (2025-10-28)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251028_110853_STE-03.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251103_125239_STE-03.csv (2025-11-03)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251103_125239_STE-03.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251110_095343_STE-03.csv (2025-11-10)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251110_095343_STE-03.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251111_110949_STE-03.csv (2025-11-11)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251111_110949_STE-03.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251112_114717_STE-03.csv (2025-11-12)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251112_114717_STE-03.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251112_122634_STE-03.csv (2025-11-12)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251112_122634_STE-03.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251122_003137_STE-03.csv (2025-11-22)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251122_003137_STE-03.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251126_141746_STE-03.csv (2025-11-26)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251126_141746_STE-03.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251127_132919_STE-03.csv (2025-11-27)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251127_132919_STE-03.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251127_133004_STE-03.csv (2025-11-27)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251127_133004_STE-03.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20260205_131455_STE-03.csv (2026-02-05)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20260205_131455_STE-03.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

## STE-04

Next I will show the plots done on the measurement point STE-04.

### 20251007_100341_STE-04.csv (2025-10-07)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251007_100341_STE-04.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251008_095114_STE-04.csv (2025-10-08)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251008_095114_STE-04.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251008_115126_STE-04.csv (2025-10-08)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251008_115126_STE-04.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251112_130310_STE-04.csv (2025-11-12)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251112_130310_STE-04.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

## STE-07

Next I will show the plots done on the measurement point STE-07.

### 20260219_112332_STE-07.csv (2026-02-19)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20260219_112332_STE-07.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20260219_144829_STE-07.csv (2026-02-19)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20260219_144829_STE-07.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20260223_075303_STE-07.csv (2026-02-23)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20260223_075303_STE-07.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20260224_134917_STE-07.csv (2026-02-24)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20260224_134917_STE-07.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

## STE-08

Next I will show the plots done on the measurement point STE-08.

### 20251118_024904_STE-08.csv (2025-11-18)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251118_024904_STE-08.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

## STE-10

Next I will show the plots done on the measurement point STE-10.

### 20251119_112337_STE-10.csv (2025-11-19)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251119_112337_STE-10.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251120_092331_STE-10.csv (2025-11-20)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251120_092331_STE-10.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

### 20251120_093239_STE-10.csv (2025-11-20)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251120_093239_STE-10.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

## STE-11

Next I will show the plots done on the measurement point STE-11.

### 20251121_025609_STE-11.csv (2025-11-21)

```{python}
#| echo: false
#| fig-align: center

import sys, os
sys.path.append(os.path.abspath("src"))
from create_plots import load_csv, create_plotly_plot

csv_path = r"data/raw\20251121_025609_STE-11.csv"
variable = "A Flow velocity [m/s]"

df = load_csv(csv_path)
fig = create_plotly_plot(df, variable, csv_path)
fig 
```

